# Generated by Django 5.1.1 on 2024-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('primary_contact_person', models.CharField(max_length=255)),
                ('secondary_contact_person', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(max_length=254)),
                ('secondary_email', models.EmailField(max_length=254)),
                ('primary_phone_no', models.CharField(max_length=15)),
                ('secondary_phone_no', models.CharField(max_length=15)),
                ('gst_no', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineerManagerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calib_engineer', models.CharField(max_length=255)),
                ('quality_manager', models.CharField(max_length=255)),
                ('certificate_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SettingPlugMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('ref_size', models.CharField(max_length=50)),
                ('nominal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SettingPlugTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=50)),
                ('calibration_report_no', models.CharField(max_length=50)),
                ('valid_upto', models.DateField()),
                ('traceability', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingRingMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('ref_size', models.CharField(max_length=50)),
                ('nominal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SettingRingTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=50)),
                ('calibration_report_no', models.CharField(max_length=50)),
                ('valid_upto', models.DateField()),
                ('traceability', models.TextField()),
            ],
        ),
    ]
