# Generated by Django 5.1.1 on 2024-10-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_workorder_workorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='customer_ref_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_date',
            field=models.CharField(max_length=50),
        ),
    ]
