# Generated by Django 5.1.1 on 2024-10-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_workorder_customer_ref_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='work_order',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='WorkOrderItem',
        ),
    ]
