# Generated by Django 5.1.1 on 2024-10-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
