# Generated by Django 5.1.1 on 2024-10-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
