# Generated by Django 5.1.1 on 2024-10-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
