# Generated by Django 5.1.1 on 2024-11-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_workorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
