# Generated by Django 5.1.1 on 2024-11-09 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_calibrationequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('master_name', models.CharField(blank=True, max_length=100)),
                ('id_no', models.CharField(blank=True, max_length=100)),
                ('calibration_no', models.CharField(blank=True, max_length=100)),
                ('valid_upto', models.CharField(blank=True, max_length=100)),
                ('traceability', models.CharField(blank=True, max_length=100)),
                ('main_calibration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='app.maincalibration')),
            ],
        ),
    ]
