# Generated by Django 5.1.1 on 2024-11-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_maincalibration_inward_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationresult',
            name='main_calibration',
        ),
        migrations.DeleteModel(
            name='CalibrationEquipment',
        ),
        migrations.DeleteModel(
            name='CalibrationResult',
        ),
        migrations.DeleteModel(
            name='MainCalibration',
        ),
    ]
