# Generated by Django 5.1.1 on 2024-11-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_maincalibration_calibrationresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationresult',
            name='main_calibration',
        ),
        migrations.DeleteModel(
            name='CalibrationEquipment',
        ),
        migrations.DeleteModel(
            name='CalibrationResult',
        ),
        migrations.DeleteModel(
            name='MainCalibration',
        ),
    ]
