# Generated by Django 5.0.14 on 2025-08-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_maincalibration_inward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='LVDTprobeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('ref_size', models.CharField(max_length=50)),
                ('nominal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LVDTprobeTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=255)),
                ('id_no', models.CharField(max_length=50)),
                ('calibration_report_no', models.CharField(max_length=50)),
                ('valid_upto', models.CharField(max_length=50)),
                ('traceability', models.TextField()),
            ],
        ),
    ]
