# Generated by Django 5.0.14 on 2025-10-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_lvdtprobemaster_lvdtprobetrace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lvdtprobemaster',
            name='nominal',
        ),
    ]
