from .login import login
from .calib import calib
from .index import index
from .inward import inward
from .master import master
from .output import output
from .report import report
from .invoice import invoice
from .keyboard import keyboard
from .customer import customer
from .delete_customer import delete_customer
from .quotation import quotation